package main

const defaultPlanJSON = `{
  "groups": [
    {"output":"01_UI_HUD.vpk","title":"Merged UI and HUD","packages":["1134792494.vpk","1195955268.vpk","1236192691.vpk","1647716531.vpk","2240665611.vpk","2256147202.vpk","2314318589.vpk","638169501.vpk","710194284.vpk","934602353.vpk","2906960647.vpk","935497493.vpk","940974914.vpk"]},
    {"output":"02_Survivors.vpk","title":"Merged Survivor Models","packages":["2683632674.vpk","2709501683.vpk","2858024805.vpk","2946874728.vpk","2963597452.vpk","3160719611.vpk","3293390651.vpk"]},
    {"output":"03_Infected.vpk","title":"Merged Infected Models","packages":["1603974683.vpk","1712169284.vpk","1777520694.vpk","1989882181.vpk","2001004696.vpk","2518548953.vpk","2595902795.vpk","3304301123.vpk","3304303150.vpk","3304309191.vpk"]},
    {"output":"04_Weapons.vpk","title":"Merged Weapons","packages":["626187474.vpk","925509260.vpk","2620798646.vpk","3227795696.vpk"]},
    {"output":"05_Environment.vpk","title":"Merged Environment","packages":["130033528.vpk","1405578190.vpk","1985052342.vpk","2228973955.vpk","2684105741.vpk","294702378.vpk","3559801225.vpk"]},
    {"output":"06_Effects.vpk","title":"Merged Visual Effects","packages":["2239530290.vpk","2398166294.vpk","3566304462.vpk","912257624.vpk"]},
    {"output":"07_Audio.vpk","title":"Merged Audio","packages":["590565930.vpk","627562239.vpk"],"exclude":["sound/weapons/machinegun_m60/gunfire/machinegun_fire_1.wav","sound/weapons/machinegun_m60/gunfire/machinegun_fire_1_incendiary.wav"]},
    {"output":"08_Gameplay.vpk","title":"Merged Gameplay Scripts","packages":["214630948.vpk","2262433022.vpk","A_连跳前置.vpk","A_连跳MOD（全模式通用）.vpk"],"overlay":{"scripts/vscripts/director_base_addon.nut":"@gameplay"}},
    {"output":"09_Sprays.vpk","title":"Merged Sprays","packages":["2788970301.vpk","2837348060.vpk","3431275706.vpk"],"overlay":{"scripts/sprays_manifest.txt":"@sprays"}},
    {"output":"10_TUMTaRA.vpk","title":"Merged TUMTaRA Maps","packages":["2189358004.vpk","2189391054.vpk","2189396300.vpk","2189405704.vpk","2189409705.vpk","2189414528.vpk","2189419829.vpk","2189441393.vpk","2189446707.vpk","2189463734.vpk","2189467576.vpk","2263388642.vpk","469986973.vpk"]},
    {"output":"11_AlwaysToast_LDR.vpk","title":"Merged AlwaysToast Long Dead Road","packages":["3325749591.vpk","3362259054.vpk","734028025.vpk"]},
    {"output":"12_Training_Map.vpk","title":"Merged Training Map","packages":["1935392108.vpk"]}
  ]
}`

const gameplayOverlay = `// Combined entry point generated by L4D2 Mod Join.
IncludeScript("admin_system");
IncludeScript("take_bot_item");
`

const spraysOverlay = `sprays_manifest
{
	"1" "1.vtf" "2" "2.vtf" "3" "3.vtf" "4" "4.vtf" "5" "5.vtf"
	"6" "6.vtf" "7" "7.vtf" "8" "8.vtf" "9" "9.vtf" "10" "10.vtf"
	"11" "11.vtf" "12" "12.vtf" "13" "13.vtf" "14" "14.vtf" "15" "15.vtf"
	"test1" "test1.vtf" "test2" "test2.vtf" "test3" "test3.vtf"
	"test4" "test4.vtf" "test5" "test5.vtf" "test6" "test6.vtf"
	"test7" "test7.vtf" "test8" "test8.vtf" "test9" "test9.vtf"
	"test10" "test10.vtf" "test11" "test11.vtf" "test12" "test12.vtf"
	"test13" "test13.vtf" "test14" "test14.vtf" "test15" "test15.vtf"
}
`
